### ISSUE TITLE
"Related deployments" naming and position

### ISSUE THREAD

**Issue by pmackay** [civic-commons/opencivic#101]
Could the titles of Related deployments be made clearer? Is each deployment going to be named "Deployment of X"? What happens with multiple deployments of same app? And could sidebar list just app and org, rather than node title? Should that list go in the content area, not the sidebar?

**Comment by sheldonrampton** [comment]
I'll review and comment on them.

**Comment by sheldonrampton** [comment]
As we discussed the other day, I've changed the Auto Entity Label setting so instead of just saying "Deployment of [application title]" it says "[Application title] deployed by [Related organizations]." To enable this change on your existing OpenCivic site without rerunning the installation profile, just revert the "AppCat deployment node" feature.
