### ISSUE TITLE
add migrate_d2d into makefile

### ISSUE THREAD

**Issue by pmackay** [civic-commons/opencivic#138]
as dependency for migrate_opencivic

**Comment by pmackay** [comment]
This is needed but worth checking if all migrate modules generally should be included or not.

**Comment by pmackay** [comment]
@dafeder @sheldonrampton guys, is it worth including various migrate modules into OC by default?

**Comment by dafeder** [comment]
Hmm. It is awesome that we have some well-built OpenCivic migrate destination classes, but I'm not sure a large majority of end users will really use them. Honestly it feels a little bloated to include all that stuff. Also, we should think about whether we really want to be maintaining that module once our own uses of it for client projects have ended. What would you think about throwing it up on github for now with a prominent link in the project page and readme file?

**Comment by dafeder** [comment]
A second option - rather than making a separate module, you could put your classes into an opencivic_core.migrate.inc file. This is how a lot of contrib modules handle exposing migrate classes without adding a migrate dependency. (See http://drupalcode.org/project/field_collection.git/tree). You could handle the drupal_d2d dependency, I think, with some conditionals, module_exists calls and error messages through drupal_set_message().

**Comment by pmackay** [comment]
I'd rather not attempt to integrate into Core currently. The module is currently in the opencivic project though - are you saying it would be better removed from there? It could stay there but the makefile not include any of the required migrate modules, if that reduces the bloat.

**Comment by pmackay** [comment]
Closing as not adding migrate modules for now.
