### ISSUE TITLE
Multiple languages are supported

### ISSUE THREAD

**Issue by pmackay** [civic-commons/opencivic#73]

**Comment by sheldonrampton** [comment]
Paul, I've merged in your latest changes to the multilingual branch, but I think some things are still missing. In order to enable actual multilingual translation of node content, the "Multilingual content" node needs to be enabled, and then individual content types need to be configured to enable translation. This should either be done in code, or it should be explained in the documentation.

**Comment by pmackay** [comment]
Yes that work on the multilingual branch is not finished yet... But thanks if you dont mind merging partly done stuff :)
