### ISSUE TITLE
Improve "Prepare site" install phase

### ISSUE THREAD

**Issue by pmackay** [civic-commons/opencivic#87]
Currently this has "Miscellaneous startup stuff " and "Finish" as stages. Surely these should be run by default?

**Comment by sheldonrampton** [comment]
Changing that will have to happen at a future stage of development. The miscellaneous startup stuff can't run during the installation profile phase right now because it creates timeout errors that I haven't been able to debug.

The "finish" stage is intended to make the "prepare site" form go away, and my assumption is that users won't always install all of the components, so they need a way to indicate when they've finished installing components.

The current UX for the prepare site form could definitely bear improvement, but that requires more thought and programming than can be done quickly, so it needs to be pushed into a future phase of work.

**Comment by pmackay** [comment]
OK to close this given ocsetup now removed?

**Comment by pmackay** [comment]
Closing as the ocsetup "Prepare" phase has now been removed.
